### ISSUE TITLE
fantasy/static land?

### ISSUE THREAD

**Issue by gautaz** [andrejewski/affection#2]
Hello,

This is more of a question than a real issue, forgive me if this is not the right place to start this discussion.

Your approach to side effects seems close to the way functional programmers handle them by using the [IO Monad](https://monet.github.io/monet.js/#io).

Currently two functional friendly specifications that I know of exist in the javascript ecosystem:
- [Fantasy Land](https://github.com/fantasyland/fantasy-land)
- [Static Land](https://github.com/rpominov/static-land)

Both of these are compatible and provide a common way to compose operations through [monad chaining](https://github.com/fantasyland/fantasy-land#chain).

Did you consider making your library compliant with one of these?
It would help people using your library with functional tools like [Sanctuary](https://github.com/sanctuary-js/sanctuary).

**Comment by andrejewski** [comment]
I encourage experimentation with trying to bridge these two efforts. Maybe an `affection-land` package which wraps `affection` could provide this compatibility.

I personally don't use any of these more established FP libraries, so I wouldn't feel comfortable contributing as I'm not sure what an idiomatic interface would look like.

One thing to emphasize is that `affection` is for describing side-effects with data, not merely deferring execution. If you see a way forward, I think it could be pretty compelling to have side-effects be more inspectable/testable in these Lands.

**Comment by gautaz** [comment]
Spring cleaning time!
There is no need to keep this issue anymore, feel free to reopen a new one if needed.
